---
title: "eds223-week1-discussion"
format: html
editor: visual
---

## Week 1 Discussion
```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```

```{r}
ei_points <- st_read(here("data", "easter_island", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("data", "easter_island", "ei_elev.tif"))
ei_borders <- st_read(here("data", "easter_island", "ei_border.gpkg"))
ei_roads <- st_read(here("data", "easter_island", "ei_roads.gpkg"))
```

```{r}
# Create map outline of Rapa Nui
tm_shape(ei_borders) +
  tm_borders() 
```
```{r}
# Expand on your single-object map to create a map of Rapa Nui

ei <- tm_shape(ei_elev) +
tm_graticules() +
  tm_raster(col.scale = tm_scale_continuous(values = c("tan", "forestgreen", "orange", "orangered")),
            col.legend = tm_legend("Elevation (m asl)")) +
tm_shape(ei_roads) +
  tm_lines(col = "black", lwd = 1, lty = "dashed") +
tm_shape(ei_borders) +
  tm_borders(col = "black") +
tm_shape(ei_points) +
  tm_symbols(shape = 24,
             size = .5,
             fill = "brown") +
tm_scale_bar() +
tm_compass(size = 2, position = c("right", "top")) +
tm_title("Easter Island")
```
```{r}
# Create interactive map
tmap_mode("view")
ei
```


